export const LOAD_INDICATORS_SUCCESS = "LOAD_INDICATORS_SUCCESS";
export const LOAD_SUBINDICATORS_SUCCESS = "LOAD_SUBINDICATORS_SUCCESS";
export const LOAD_SUBINDICATORDETAILS_SUCCESS = "LOAD_SUBINDICATORDETAILS_SUCCESS";

export const LOAD_RESOURCES_SUCCESS = "LOAD_RESOURCES_SUCCESS";
export const SEARCH_RESOURCES_SUCCESS = "SEARCH_RESOURCES_SUCCESS";
export const LOADMORE_RESOURCES_SUCCESS = "LOADMORE_RESOURCES_SUCCESS";
export const SET_PAGE_SUCCESS = "SET_PAGE_SUCCESS";
export const LOAD_RESOURCEPAGE_SUCCESS = "LOAD_RESOURCEPAGE_SUCCESS";
export const LOAD_RECENT_RESOURCE_SUCCESS = "LOAD_RECENT_RESOURCE_SUCCESS";

export const LOAD_SEARCHES_SUCCESS = "LOAD_SEARCHES_SUCCESS";
export const SEARCH_SEARCHES_SUCCESS = "SEARCH_SEARCHES_SUCCESS";
export const LOADMORE_SEARCHES_SUCCESS = "LOADMORE_SEARCHES_SUCCESS";
export const SET_SEARCH_PAGE_SUCCESS = "SET_SEARCH_PAGE_SUCCESS";
export const LOAD_SEARCHPAGE_SUCCESS = "LOAD_SEARCHPAGE_SUCCESS";
export const LOAD_RECENT_SEARCH_SUCCESS = "LOAD_RECENT_SEARCH_SUCCESS";

export const LOAD_WHATWORKS_SUCCESS = "LOAD_WHATWORKS_SUCCESS";
export const FILTER_WHATWORKS_SUCCESS = "FILTER_WHATWORKS_SUCCESS";

export const LOAD_BLOG_SUCCESS = "LOAD_BLOG_SUCCESS";
export const SEARCH_BLOG_SUCCESS = "SEARCH_BLOG_SUCCESS";
export const LOADMORE_POSTS_SUCCESS = "LOADMORE_POSTS_SUCCESS";
export const SET_BLOG_PAGE_SUCCESS = "SET_BLOG_PAGE_SUCCESS";
export const LOAD_BLOGPAGE_SUCCESS = "LOAD_BLOGPAGE_SUCCESS";
export const LOAD_RECENT_BLOG_SUCCESS = "LOAD_RECENT_BLOG_SUCCESS";

export const LOAD_CAL_EVENTS_SUCCESS = "LOAD_CAL_EVENTS_SUCCESS";
export const LOAD_EVENTS_SUCCESS = "LOAD_EVENTS_SUCCESS";
export const SEARCH_EVENTS_SUCCESS = "SEARCH_EVENTS_SUCCESS";
export const LOADMORE_EVENTS_SUCCESS = "LOADMORE_EVENTS_SUCCESS";
export const SET_EVENT_PAGE_SUCCESS = "SET_EVENT_PAGE_SUCCESS";
export const LOAD_EVENTPAGE_SUCCESS = "LOAD_EVENTPAGE_SUCCESS";
export const LOAD_RECENT_EVENT_SUCCESS = "LOAD_RECENT_EVENT_SUCCESS";

export const LOAD_STORY_SUCCESS = "LOAD_STORY_SUCCESS";
export const SEARCH_STORY_SUCCESS = "SEARCH_STORY_SUCCESS";
export const LOADMORE_STORY_SUCCESS = "LOADMORE_STORY_SUCCESS";
export const SET_STORY_PAGE_SUCCESS = "SET_STORY_PAGE_SUCCESS";
export const LOAD_STORYPAGE_SUCCESS = "LOAD_STORYPAGE_SUCCESS";
export const LOAD_RECENT_STORY_SUCCESS = "LOAD_RECENT_STORY_SUCCESS";
